# Generated by Django 3.2 on 2022-02-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('Equipment', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
                ('Picture', models.CharField(max_length=4000000)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('HistortNumber', models.AutoField(primary_key=True, serialize=False)),
                ('Equipment', models.CharField(max_length=50)),
                ('Action', models.CharField(max_length=50)),
                ('DateTime', models.DateTimeField()),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('Mataterial', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
                ('Picture', models.CharField(max_length=4000000)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('Username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
