# Generated by Django 3.2 on 2022-02-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='DateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
