# Generated by Django 3.2 on 2022-02-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0002_alter_history_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='HistortNumber',
            new_name='HistoryNumber',
        ),
    ]
