# Generated by Django 3.2 on 2022-02-23 04:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0003_rename_histortnumber_history_historynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='DateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
