# Generated by Django 3.2 on 2022-02-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0005_auto_20220223_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='HistoryNumber',
        ),
        migrations.AlterField(
            model_name='history',
            name='Equipment',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='pictures/Material'),
        ),
    ]
