# Generated by Django 3.2 on 2022-02-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0006_auto_20220223_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='order',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='history',
            name='order',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='material',
            name='order',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Equipment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='Equipment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='Material',
            field=models.CharField(max_length=50),
        ),
    ]
