# Generated by Django 3.2 on 2022-02-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0007_auto_20220223_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='order',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
