# Generated by Django 3.2 on 2022-02-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0008_alter_history_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='order',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='order',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
