# Generated by Django 3.2 on 2022-02-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0009_auto_20220224_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
