# Generated by Django 3.2 on 2022-03-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0010_history_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='Category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='Type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
