# Generated by Django 3.2 on 2022-03-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0012_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='Material',
        ),
        migrations.AddField(
            model_name='storage',
            name='Brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='storage',
            name='Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
