# Generated by Django 3.2 on 2022-03-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0014_auto_20220303_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('order', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Brand', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
