# Generated by Django 3.2 on 2022-03-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0016_history_name_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='equipment',
        ),
        migrations.DeleteModel(
            name='material',
        ),
        migrations.AlterField(
            model_name='storage',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='storage'),
        ),
    ]
