# Generated by Django 3.2 on 2022-03-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0017_auto_20220303_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='masterkey',
            field=models.CharField(default='TNS<django.db.models.fields.AutoField>', max_length=50),
        ),
    ]
