# Generated by Django 3.2 on 2022-03-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0018_storage_masterkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='masterkey',
        ),
    ]
