# Generated by Django 3.2 on 2022-03-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0019_remove_storage_masterkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='Masterkey',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
