# Generated by Django 3.2 on 2022-03-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0021_equipment_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Masterkey',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
