# Generated by Django 3.2 on 2022-03-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0022_history_masterkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('order', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Category', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('order', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='equipment',
        ),
        migrations.DeleteModel(
            name='material',
        ),
    ]
