# Generated by Django 3.2 on 2022-03-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0023_auto_20220306_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='Prefix',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
