# Generated by Django 3.2 on 2022-03-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_tns_app', '0024_type_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='Thai_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
